### ISSUE TITLE
Creation de la liste de mots.

### ISSUE THREAD

**Issue by lingani** [stvsank/DI-Bootcamp-Stage1#1]
# J'aurais préférer que tu ne mettes pas d'espace après chaque mot.
# et que dans la fonction de creation des phrases tu ajoutes les espaces la-bas.

#list
def get_words_from_file():
    with open('mot.txt') as f:
        mot = []
        for line in f:
            # mot.append(line[0:len(line)-1]+' ')
            mot.append(line[0:len(line)-1]) # Correct
    return mot

**Comment by stvsank** [comment]
D'accord Monsieur, merci.

Le mer. 5 oct. 2022 à 10:27, Malick Lingani ***@***.***> a
écrit :
